---
- name: Install the latest OpenSSL/OpenSSH
  any_errors_fatal: true
  hosts: all
  roles:
    - {role: iorchard.openssl, tags: openssl}
    - {role: iorchard.openssh, tags: openssh}
    - {role: iorchard.kernel, tags: kernel}
...
