---
- name: Install | Get kernel package
  get_url:
    url: "{{ kernel_pkg }}"
    dest: "/tmp/kernel.rpm"
  delegate_to: "{{ groups['deployer'][0] }}"
  run_once: true
  tags:
    - install

- name: Install | Copy kernel package to other hosts
  copy:
    src: "/tmp/kernel.rpm"
    dest: "/tmp/kernel.rpm"
  when: inventory_hostname != groups['deployer'][0]
  tags:
    - install

- name: Install | Install kernel
  yum:
    name: "/tmp/kernel.rpm"
    state: present
  become: true
  tags:
    - install

- name: Install | Get the installed kernel packages
  yum:
    list: kernel
  register: kernel_list
  tags:
    - install

- name: Test | List the installed kernels (version-release)
  debug:
    msg: "Desired kernel: {{ kernel_version }}-{{ kernel_release }} | Installed kernels: {% for r in kernel_list.results %}{% if r.yumstate == 'installed' %}{{ r.version }}-{{ r.release }}, {%  endif %}{%  endfor %}"
  tags:
    - install
...
